theme = "onedark"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor]
true-color = true
line-number = "relative"
mouse = false
rulers = [80]
scrolloff = 20
shell = ["zsh", "-c"]
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true